
## Data Description

•	Rank: A unique integer identifier that ranks the video games based on a specific criterion (likely sales).
    
•	Name: The name of the video game.
    
•	Platform: The gaming platform on which the video game was released (e.g., PS4, Xbox One, PC).
    
•	Year: The year the game was released. This column has some missing values, with 16,327 non-null entries out of 16,598.
    
•	Genre: The genre of the video game (e.g., Action, Sports, RPG).
    
•	Publisher: The company that published the video game. There are a few missing values, with 16,540 non-null entries.
    
•	NA_Sales: Sales in North America, measured in millions of units.
    
•	EU_Sales: Sales in Europe, measured in millions of units.
    
•	JP_Sales: Sales in Japan, measured in millions of units.
    
•	Other_Sales: Sales in regions other than North America, Europe, and Japan, measured in millions of units.
    
•	Global_Sales: The total global sales of the video game, measured in millions of units.

In [146]:
import pandas as pd

In [147]:
import numpy as np

In [148]:
df=pd.read_csv("vgsales_online_game.csv")

In [149]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [150]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [151]:
df.tail()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [152]:
df.shape

(16598, 11)

In [153]:
df.shape[0]

16598

In [154]:
df.shape[1]

11

In [155]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

### Information of the dataset:
* columns=11
* rows=16598
* Data types
     float =6
     integer = 1
     object = 4
* Occur Null values
  Year = 271
  Publisher = 58

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [157]:
df.isnull().sum()
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

### Description of the dataset

In [158]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [159]:
df.describe(include='object')

                               Name Platform   Genre        Publisher
count                         16598    16598   16598            16540
unique                        11493       31      12              578
top     Need for Speed: Most Wanted       DS  Action  Electronic Arts
freq                             12     2163    3316             1351

In [160]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Rank,16598.0,NaN,NaN,NaN,8300.605254,4791.853933,1.0,4151.25,8300.5,12449.75,16600.0
Name,16598,11493,Need for Speed: Most Wanted,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Platform,16598,31,DS,2163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,16327.0,NaN,NaN,NaN,2006.406443,5.828981,1980.0,2003.0,2007.0,2010.0,2020.0
Genre,16598,12,Action,3316,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Publisher,16540,578,Electronic Arts,1351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NA_Sales,16598.0,NaN,NaN,NaN,0.264667,0.816683,0.0,0.0,0.08,0.24,41.49
EU_Sales,16598.0,NaN,NaN,NaN,0.146652,0.505351,0.0,0.0,0.02,0.11,29.02
JP_Sales,16598.0,NaN,NaN,NaN,0.077782,0.309291,0.0,0.0,0.0,0.04,10.22
Other_Sales,16598.0,NaN,NaN,NaN,0.048063,0.188588,0.0,0.0,0.01,0.04,10.57
Global_Sales,16598.0,NaN,NaN,NaN,0.537441,1.555028,0.01,0.06,0.17,0.47,82.74

### Unique values in each columns

In [161]:
df.nunique()

Rank            16598
Name            11493
Platform           31
Year               39
Genre              12
Publisher         578
NA_Sales          409
EU_Sales          305
JP_Sales          244
Other_Sales       157
Global_Sales      623
dtype: int64

In [162]:
for i in df.columns:
    print(i,':',df[i].unique())

Rank : [    1     2     3 ... 16598 16599 16600]
Name : ['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' ... 'Plushees'
 'Woody Woodpecker in Crazy Castle 5' 'Know How 2']
Platform : ['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' '3DS' 'PS4' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'GC' 'WiiU' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
Year : [2006. 1985. 2008. 2009. 1996. 1989. 1984. 2005. 1999. 2007. 2010. 2013.
 2004. 1990. 1988. 2002. 2001. 2011. 1998. 2015. 2012. 2014. 1992. 1997.
 1993. 1994. 1982. 2003. 1986. 2000.   nan 1995. 2016. 1991. 1981. 1987.
 1980. 1983. 2020. 2017.]
Genre : ['Sports' 'Platform' 'Racing' 'Role-Playing' 'Puzzle' 'Misc' 'Shooter'
 'Simulation' 'Action' 'Fighting' 'Adventure' 'Strategy']
Publisher : ['Nintendo' 'Microsoft Game Studios' 'Take-Two Interactive'
 'Sony Computer Entertainment' 'Activision' 'Ubisoft' 'Bethesda Softworks'
 'Electronic Arts' 'Sega' 'SquareSoft' 'Atari' '505 Games' 'Capcom'
 'GT Interactive' 'Konami Digital Entertainment'
 'Sony Computer Entertainment Europe' 'Square Enix' 'LucasArts'
 'Virgin Interactive' 'Warner Bros. Interactive Entertainment'
 'Universal Interactive' 'Eidos Interactive' 'RedOctane' 'Vivendi Games'
 'Enix Corporation' 'Namco Bandai Games' 'Palcom' 'Hasbro Interactive'
 'THQ' 'Fox Interactive' 'Acclaim Entertainment' 'MTV Games'
 'Disney Interactive Studios' nan 'Majesco Entertainment' 'Codemasters'
 'Red Orb' 'Level 5' 'Arena Entertainment' 'Midway Games' 'JVC'
 'Deep Silver' '989 Studios' 'NCSoft' 'UEP Systems' 'Parker Bros.' 'Maxis'
 'Imagic' 'Tecmo Koei' 'Valve Software' 'ASCII Entertainment' 'Mindscape'
 'Infogrames' 'Unknown' 'Square' 'Valve' 'Activision Value' 'Banpresto'
 'D3Publisher' 'Oxygen Interactive' 'Red Storm Entertainment'
 'Video System' 'Hello Games' 'Global Star' 'Gotham Games'
 'Westwood Studios' 'GungHo' 'Crave Entertainment' 'Hudson Soft' 'Coleco'
 'Rising Star Games' 'Atlus' 'TDK Mediactive' 'ASC Games' 'Zoo Games'
 'Accolade' 'Sony Online Entertainment' '3DO' 'RTL' 'Natsume'
 'Focus Home Interactive' 'Alchemist' 'Black Label Games'
 'SouthPeak Games' 'Mastertronic' 'Ocean' 'Zoo Digital Publishing'
 'Psygnosis' 'City Interactive' 'Empire Interactive' 'Success' 'Compile'
 'Russel' 'Taito' 'Agetec' 'GSP' 'Microprose' 'Play It'
 'Slightly Mad Studios' 'Tomy Corporation' 'Sammy Corporation'
 'Koch Media' 'Game Factory' 'Titus' 'Marvelous Entertainment' 'Genki'
 'Mojang' 'Pinnacle' 'CTO SpA' 'TalonSoft' 'Crystal Dynamics' 'SCi'
 'Quelle' 'mixi, Inc' 'Rage Software' 'Ubisoft Annecy' 'Scholastic Inc.'
 'Interplay' 'Mystique' 'ChunSoft' 'Square EA'
 '20th Century Fox Video Games' 'Avanquest Software'
 'Hudson Entertainment' 'Nordic Games' 'Men-A-Vision' 'Nobilis'
 'Big Ben Interactive' 'Touchstone' 'Spike' 'Jester Interactive'
 'Nippon Ichi Software' 'LEGO Media' 'Quest' 'Illusion Softworks'
 'Tigervision' 'Funbox Media' 'Rocket Company' 'Metro 3D'
 'Mattel Interactive' 'IE Institute' 'Rondomedia'
 'Sony Computer Entertainment America' 'Universal Gamex' 'Ghostlight'
 'Wizard Video Games' 'BMG Interactive Entertainment' 'PQube'
 'Trion Worlds' 'Laguna' 'Ignition Entertainment' 'Takara'
 'Kadokawa Shoten' 'Destineer' 'Enterbrain' 'Xseed Games' 'Imagineer'
 'System 3 Arcade Software' 'CPG Products' 'Aruze Corp' 'Gamebridge'
 'Midas Interactive Entertainment' 'Jaleco' 'Answer Software' 'XS Games'
 'Activision Blizzard' 'Pack In Soft' 'Rebellion' 'Xplosiv' 'Ultravision'
 'GameMill Entertainment' 'Wanadoo' 'NovaLogic' 'Telltale Games' 'Epoch'
 'BAM! Entertainment' 'Knowledge Adventure' 'Mastiff' 'Tetris Online'
 'Harmonix Music Systems' 'ESP' 'TYO' 'Telegames' 'Mud Duck Productions'
 'Screenlife' 'Pioneer LDC' 'Magical Company' 'Mentor Interactive' 'Kemco'
 'Human Entertainment' 'Avanquest' 'Data Age' 'Electronic Arts Victor'
 'Black Bean Games' 'Jack of All Games' '989 Sports' 'Takara Tomy'
 'Media Rings' 'Elf' 'Kalypso Media' 'Starfish' 'Zushi Games' 'Jorudan'
 'Destination Software, Inc' 'New' 'Brash Entertainment'
 'ITT Family Games' 'PopCap Games' 'Home Entertainment Suppliers'
 'Ackkstudios' 'Starpath Corp.' 'P2 Games' 'BPS' 'Gathering of Developers'
 'NewKidCo' 'Storm City Games' 'CokeM Interactive' 'CBS Electronics'
 'Magix' 'Marvelous Interactive' 'Nihon Falcom Corporation'
 'Wargaming.net' 'Angel Studios' 'Arc System Works' 'Playmates'
 'SNK Playmore' 'Hamster Corporation' 'From Software' 'Nippon Columbia'
 'Nichibutsu' 'Little Orbit' 'Conspiracy Entertainment'
 'DTP Entertainment' 'Hect' 'Mumbo Jumbo' 'Pacific Century Cyber Works'
 'Indie Games' 'Liquid Games' 'NEC' 'Axela' 'ArtDink' 'Sunsoft' 'Gust'
 'SNK' 'NEC Interchannel' 'FuRyu' 'Xing Entertainment' 'ValuSoft'
 'Victor Interactive' 'Detn8 Games' 'American Softworks' 'Nordcurrent'
 'Bomb' 'Falcom Corporation' 'AQ Interactive' 'CCP' 'Milestone S.r.l.'
 'Sears' 'JoWood Productions' 'Seta Corporation' 'On Demand' 'NCS' 'Aspyr'
 'Gremlin Interactive Ltd' 'Agatsuma Entertainment' 'Compile Heart'
 'Culture Brain' 'Mad Catz' 'Shogakukan' 'Merscom LLC'
 'Rebellion Developments' 'Nippon Telenet' 'TDK Core' 'bitComposer Games'
 'Foreign Media Games' 'Astragon' 'SSI' 'Kadokawa Games' 'Idea Factory'
 'Performance Designed Products' 'Asylum Entertainment' 'Core Design Ltd.'
 'PlayV' 'UFO Interactive' 'Idea Factory International'
 'Playlogic Game Factory' 'Essential Games' 'Adeline Software' 'Funcom'
 'Panther Software' 'Blast! Entertainment Ltd' 'Game Life' 'DSI Games'
 'Avalon Interactive' 'Popcorn Arcade' 'Neko Entertainment'
 'Vir2L Studios' 'Aques' 'Syscom' 'White Park Bay Software' 'System 3'
 'Vatical Entertainment' 'Daedalic' 'EA Games' 'Media Factory' 'Vic Tokai'
 'The Adventure Company' 'Game Arts' 'Broccoli' 'Acquire'
 'General Entertainment' 'Excalibur Publishing' 'Imadio'
 'Swing! Entertainment' 'Sony Music Entertainment' 'Aqua Plus'
 'Paradox Interactive' 'Hip Interactive' 'DreamCatcher Interactive'
 'Tripwire Interactive' 'Sting' 'Yacht Club Games' 'SCS Software'
 'Bigben Interactive' 'Havas Interactive' 'Slitherine Software' 'Graffiti'
 'Funsta' 'Telstar' 'U.S. Gold' 'DreamWorks Interactive'
 'Data Design Interactive' 'MTO' 'DHM Interactive' 'FunSoft' 'SPS'
 'Bohemia Interactive' 'Reef Entertainment' 'Tru Blu Entertainment' 'Moss'
 'T&E Soft' 'O-Games' 'Aksys Games' 'NDA Productions' 'Data East'
 'Time Warner Interactive' 'Gainax Network Systems' 'Daito'
 'O3 Entertainment' 'Gameloft' 'Xicat Interactive'
 'Simon & Schuster Interactive' 'Valcon Games' 'PopTop Software' 'TOHO'
 'HMH Interactive' '5pb' 'Cave' 'CDV Software Entertainment' 'Microids'
 'PM Studios' 'Paon' 'Micro Cabin' 'GameTek' 'Benesse' 'Type-Moon'
 'Enjoy Gaming ltd.' 'Asmik Corp' 'Interplay Productions'
 'Asmik Ace Entertainment' 'inXile Entertainment' 'Image Epoch'
 'Phantom EFX' 'Evolved Games' 'responDESIGN' 'Culture Publishers'
 'Griffin International' 'Hackberry' 'Hearty Robin' 'Nippon Amuse'
 'Origin Systems' 'Seventh Chord' 'Mitsui' 'Milestone' 'Abylight'
 'Flight-Plan' 'Glams' 'Locus' 'Warp' 'Daedalic Entertainment'
 'Alternative Software' 'Myelin Media' 'Mercury Games'
 'Irem Software Engineering' 'Sunrise Interactive' 'Elite'
 'Evolution Games' 'Tivola' 'Global A Entertainment' 'Edia' 'Athena'
 'Aria' 'Gamecock' 'Tommo' 'Altron' 'Happinet' 'iWin' 'Media Works'
 'Fortyfive' 'Revolution Software' 'Imax' 'Crimson Cow' '10TACLE Studios'
 'Groove Games' 'Pack-In-Video' 'Insomniac Games'
 'Ascaron Entertainment GmbH' 'Asgard' 'Ecole' 'Yumedia' 'Phenomedia'
 'HAL Laboratory' 'Grand Prix Games' 'DigiCube' 'Creative Core'
 'Kaga Create' 'WayForward Technologies' 'LSP Games' 'ASCII Media Works'
 'Coconuts Japan' 'Arika' 'Ertain' 'Marvel Entertainment' 'Prototype'
 'TopWare Interactive' 'Phantagram' '1C Company' 'The Learning Company'
 'TechnoSoft' 'Vap' 'Misawa' 'Tradewest' 'Team17 Software' 'Yeti' 'Pow'
 'Navarre Corp' 'MediaQuest' 'Max Five' 'Comfort'
 'Monte Christo Multimedia' 'Pony Canyon' 'Riverhillsoft' 'Summitsoft'
 'Milestone S.r.l' 'Playmore' 'MLB.com' 'Kool Kizz' 'Flashpoint Games'
 '49Games' 'Legacy Interactive' 'Alawar Entertainment' 'CyberFront'
 'Cloud Imperium Games Corporation' 'Societa' 'Virtual Play Games'
 'Interchannel' 'Sonnet' 'Experience Inc.' 'Zenrin' 'Iceberg Interactive'
 'Ivolgamus' '2D Boy' 'MC2 Entertainment' 'Kando Games' 'Just Flight'
 'Office Create' 'Mamba Games' 'Fields' 'Princess Soft'
 'Maximum Family Games' 'Berkeley' 'Fuji' 'Dusenberry Martin Racing'
 'imageepoch Inc.' 'Big Fish Games' 'Her Interactive' 'Kamui' 'ASK'
 'Headup Games' 'KSS' 'Cygames' 'KID' 'Quinrose' 'Sunflowers'
 'dramatic create' 'TGL' 'Encore' 'Extreme Entertainment Group'
 'Intergrow' 'G.Rev' 'Sweets' 'Kokopeli Digital Studios' 'Number None'
 'Nexon' 'id Software' 'BushiRoad' 'Tryfirst' 'Strategy First' '7G//AMES'
 'GN Software' "Yuke's" 'Easy Interactive' 'Licensed 4U'
 'FuRyu Corporation' 'Lexicon Entertainment' 'Paon Corporation'
 'Kids Station' 'GOA' 'Graphsim Entertainment' 'King Records'
 'Introversion Software' 'Minato Station' 'Devolver Digital' 'Blue Byte'
 'Gaga' 'Yamasa Entertainment' 'Plenty' 'Views' 'fonfun' 'NetRevo'
 'Codemasters Online' 'Quintet' 'Phoenix Games' 'Dorart' 'Marvelous Games'
 'Focus Multimedia' 'Imageworks' 'Karin Entertainment' 'Aerosoft'
 'Technos Japan Corporation' 'Gakken' 'Mirai Shounen' 'Datam Polystar'
 'Saurus' 'HuneX' 'Revolution (Japan)' 'Giza10' 'Visco' 'Alvion' 'Mycom'
 'Giga' 'Warashi' 'System Soft' 'Sold Out' 'Lighthouse Interactive'
 'Masque Publishing' 'RED Entertainment' 'Michaelsoft'
 'Media Entertainment' 'New World Computing' 'Genterprise'
 'Interworks Unlimited, Inc.' 'Boost On' 'Stainless Games'
 'EON Digital Entertainment' 'Epic Games' 'Naxat Soft'
 'Ascaron Entertainment' 'Piacci' 'Nitroplus' 'Paradox Development'
 'Otomate' 'Ongakukan' 'Commseed' 'Inti Creates' 'Takuyo'
 'Interchannel-Holon' 'Rain Games' 'UIG Entertainment']
NA_Sales : [4.149e+01 2.908e+01 1.585e+01 1.575e+01 1.127e+01 2.320e+01 1.138e+01
 1.403e+01 1.459e+01 2.693e+01 9.070e+00 9.810e+00 9.000e+00 8.940e+00
 9.090e+00 1.497e+01 7.010e+00 9.430e+00 1.278e+01 4.750e+00 6.420e+00
 1.083e+01 9.540e+00 9.630e+00 8.410e+00 6.060e+00 5.570e+00 3.440e+00
 6.850e+00 9.030e+00 5.890e+00 9.670e+00 5.170e+00 5.770e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.750e+00 5.980e+00 2.550e+00
 4.740e+00 7.970e+00 3.800e+00 4.400e+00 6.910e+00 3.010e+00 6.160e+00
 4.230e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.990e+00
 4.340e+00 5.080e+00 6.050e+00 6.720e+00 7.030e+00 5.550e+00 3.660e+00
 6.630e+00 4.090e+00 5.840e+00 3.880e+00 5.910e+00 4.360e+00 5.580e+00
 2.010e+00 4.460e+00 5.030e+00 3.540e+00 1.110e+00 1.790e+00 6.820e+00
 3.810e+00 2.910e+00 1.060e+00 9.800e-01 5.800e+00 2.580e+00 2.280e+00
 2.820e+00 7.280e+00 2.900e+00 2.930e+00 2.800e+00 4.100e+00 3.780e+00
 5.390e+00 3.240e+00 4.790e+00 3.830e+00 4.520e+00 3.510e+00 2.850e+00
 3.270e+00 3.680e+00 4.410e+00 3.130e+00 2.470e+00 4.120e+00 4.140e+00
 7.800e-01 2.710e+00 2.770e+00 3.230e+00 3.500e+00 4.150e+00 3.100e+00
 8.400e-01 1.670e+00 2.790e+00 7.900e-01 3.250e+00 3.740e+00 2.640e+00
 4.980e+00 2.570e+00 3.640e+00 3.700e+00 4.010e+00 7.000e-02 3.110e+00
 3.920e+00 4.050e+00 2.450e+00 4.470e+00 2.630e+00 3.180e+00 2.410e+00
 1.880e+00 6.600e-01 2.260e+00 2.490e+00 2.970e+00 2.540e+00 2.950e+00
 3.280e+00 2.700e+00 2.990e+00 4.700e-01 3.140e+00 2.620e+00 3.210e+00
 2.720e+00 2.070e+00 1.970e+00 1.740e+00 2.180e+00 3.020e+00 1.620e+00
 1.920e+00 3.330e+00 1.220e+00 2.300e+00 4.260e+00 6.500e-01 2.430e+00
 2.320e+00 1.080e+00 1.900e+00 2.100e+00 9.600e-01 1.640e+00 1.980e+00
 3.590e+00 3.220e+00 1.960e+00 2.660e+00 1.700e+00 6.000e-01 3.400e+00
 2.050e+00 3.420e+00 2.590e+00 3.360e+00 3.060e+00 3.490e+00 3.390e+00
 1.850e+00 2.310e+00 3.980e+00 2.890e+00 0.000e+00 2.740e+00 2.560e+00
 1.910e+00 5.700e-01 2.800e-01 2.360e+00 1.730e+00 3.050e+00 1.870e+00
 1.940e+00 2.080e+00 2.290e+00 2.420e+00 2.600e+00 1.890e+00 1.780e+00
 1.550e+00 3.190e+00 4.180e+00 4.210e+00 3.630e+00 2.000e-01 1.540e+00
 2.670e+00 1.000e-01 2.190e+00 2.030e+00 3.030e+00 2.200e+00 9.200e-01
 2.750e+00 4.000e+00 2.510e+00 2.110e+00 2.230e+00 1.410e+00 3.000e+00
 1.460e+00 8.800e-01 1.300e+00 1.280e+00 2.250e+00 2.020e+00 3.380e+00
 2.040e+00 3.790e+00 1.400e+00 4.030e+00 1.650e+00 7.100e-01 2.140e+00
 1.420e+00 2.130e+00 2.650e+00 2.350e+00 1.200e-01 1.680e+00 1.120e+00
 2.780e+00 1.380e+00 2.150e+00 1.180e+00 1.330e+00 6.700e-01 1.530e+00
 1.150e+00 9.300e-01 2.120e+00 2.480e+00 1.600e-01 8.700e-01 2.210e+00
 1.440e+00 1.490e+00 1.140e+00 2.400e+00 1.820e+00 1.370e+00 1.930e+00
 5.800e-01 1.590e+00 2.530e+00 2.330e+00 5.000e-02 1.610e+00 2.380e+00
 1.570e+00 1.560e+00 1.230e+00 1.660e+00 1.170e+00 2.840e+00 5.900e-01
 2.090e+00 2.390e+00 1.340e+00 1.130e+00 8.600e-01 1.750e+00 4.600e-01
 1.430e+00 1.630e+00 1.450e+00 1.470e+00 1.990e+00 1.500e+00 8.000e-01
 1.360e+00 5.000e-01 2.500e-01 9.500e-01 1.270e+00 3.000e-02 1.720e+00
 7.300e-01 1.760e+00 1.350e+00 1.480e+00 1.520e+00 1.860e+00 2.060e+00
 6.800e-01 9.100e-01 1.690e+00 8.000e-02 1.290e+00 2.170e+00 2.500e+00
 1.010e+00 1.580e+00 1.040e+00 2.220e+00 1.830e+00 6.100e-01 1.840e+00
 9.900e-01 1.510e+00 9.000e-02 4.000e-01 2.520e+00 1.320e+00 2.000e-02
 1.050e+00 2.900e-01 1.190e+00 8.900e-01 3.000e-01 1.200e+00 1.240e+00
 1.250e+00 1.070e+00 1.020e+00 6.900e-01 1.950e+00 2.000e+00 7.600e-01
 6.300e-01 9.000e-01 4.800e-01 6.400e-01 3.700e-01 1.310e+00 1.500e-01
 1.210e+00 4.900e-01 1.300e-01 1.810e+00 1.260e+00 8.100e-01 7.700e-01
 1.000e+00 1.160e+00 1.390e+00 8.500e-01 5.200e-01 5.100e-01 3.800e-01
 6.200e-01 1.090e+00 1.710e+00 1.030e+00 3.400e-01 1.600e+00 5.400e-01
 1.400e-01 1.000e-02 8.200e-01 8.300e-01 1.100e-01 9.400e-01 1.770e+00
 7.000e-01 9.700e-01 7.500e-01 3.500e-01 7.200e-01 7.400e-01 1.800e-01
 1.100e+00 5.600e-01 2.600e-01 2.100e-01 2.200e-01 5.300e-01 5.500e-01
 2.300e-01 3.900e-01 3.200e-01 4.500e-01 4.100e-01 3.100e-01 2.400e-01
 6.000e-02 4.300e-01 4.400e-01 1.900e-01 4.000e-02 1.700e-01 3.600e-01
 3.300e-01 2.700e-01 4.200e-01]
EU_Sales : [2.902e+01 3.580e+00 1.288e+01 1.101e+01 8.890e+00 2.260e+00 9.230e+00
 9.200e+00 7.060e+00 6.300e-01 1.100e+01 7.570e+00 6.180e+00 8.030e+00
 8.590e+00 4.940e+00 9.270e+00 4.000e-01 3.750e+00 9.260e+00 4.520e+00
 2.710e+00 3.440e+00 5.310e+00 5.490e+00 3.900e+00 3.280e+00 5.360e+00
 5.090e+00 4.280e+00 5.040e+00 3.730e+00 4.050e+00 5.810e+00 5.880e+00
 4.300e+00 3.630e+00 5.820e+00 4.510e+00 2.610e+00 4.440e+00 3.520e+00
 3.910e+00 2.830e+00 2.770e+00 2.850e+00 1.000e-02 3.400e+00 3.370e+00
 2.040e+00 3.100e+00 3.870e+00 2.990e+00 4.880e+00 3.690e+00 3.760e+00
 2.150e+00 2.650e+00 3.110e+00 3.150e+00 2.630e+00 1.980e+00 1.940e+00
 3.070e+00 2.360e+00 2.470e+00 2.890e+00 3.420e+00 2.380e+00 1.710e+00
 2.320e+00 1.880e+00 2.860e+00 1.240e+00 6.060e+00 3.530e+00 1.530e+00
 2.300e+00 1.860e+00 5.050e+00 6.420e+00 2.010e+00 2.070e+00 1.720e+00
 1.780e+00 4.500e-01 2.420e+00 3.290e+00 3.300e+00 1.890e+00 2.170e+00
 1.180e+00 1.350e+00 1.900e+00 2.130e+00 2.190e+00 2.090e+00 3.030e+00
 2.930e+00 2.220e+00 1.750e+00 1.040e+00 1.770e+00 2.210e+00 4.320e+00
 3.020e+00 2.750e+00 2.800e+00 2.350e+00 2.640e+00 1.920e+00 2.250e+00
 2.780e+00 4.290e+00 1.840e+00 9.300e-01 2.560e+00 1.300e+00 1.580e+00
 1.200e+00 1.560e+00 1.970e+00 1.260e+00 8.300e-01 6.210e+00 1.620e+00
 1.740e+00 1.830e+00 2.280e+00 0.000e+00 2.050e+00 6.900e-01 1.630e+00
 1.470e+00 1.950e+00 6.000e-01 1.650e+00 1.910e+00 5.700e-01 1.640e+00
 1.110e+00 1.870e+00 2.290e+00 2.510e+00 9.600e-01 1.120e+00 7.700e-01
 1.080e+00 7.900e-01 2.480e+00 2.460e+00 2.600e-01 7.500e-01 1.250e+00
 9.800e-01 3.480e+00 7.400e-01 2.020e+00 2.230e+00 6.100e-01 1.690e+00
 1.430e+00 1.160e+00 1.380e+00 1.060e+00 1.360e+00 1.030e+00 1.730e+00
 1.540e+00 9.900e-01 1.680e+00 2.000e+00 3.140e+00 1.570e+00 1.310e+00
 2.100e+00 1.410e+00 9.100e-01 1.990e+00 1.390e+00 1.150e+00 9.200e-01
 2.400e-01 1.510e+00 1.400e-01 1.290e+00 2.390e+00 1.050e+00 5.000e-01
 1.790e+00 5.800e-01 1.270e+00 1.340e+00 1.020e+00 2.270e+00 2.550e+00
 2.790e+00 4.400e-01 4.800e-01 2.700e-01 2.100e-01 5.100e-01 1.500e+00
 1.520e+00 4.000e-02 1.280e+00 1.550e+00 2.120e+00 2.800e-01 8.900e-01
 1.960e+00 7.600e-01 1.170e+00 4.900e-01 1.610e+00 1.140e+00 6.500e-01
 1.440e+00 1.930e+00 1.370e+00 1.400e+00 8.800e-01 7.300e-01 1.220e+00
 1.130e+00 8.100e-01 9.700e-01 1.800e+00 1.090e+00 6.800e-01 1.420e+00
 6.700e-01 2.400e+00 1.330e+00 1.210e+00 1.660e+00 9.400e-01 3.900e-01
 3.800e-01 1.010e+00 1.070e+00 1.590e+00 1.900e-01 2.110e+00 3.000e-01
 1.000e-01 7.200e-01 8.700e-01 5.600e-01 1.600e-01 8.600e-01 6.200e-01
 1.000e+00 8.200e-01 8.400e-01 6.400e-01 8.000e-01 4.700e-01 3.200e-01
 7.100e-01 1.850e+00 2.430e+00 5.500e-01 5.300e-01 9.000e-02 1.190e+00
 7.000e-02 2.000e-01 7.000e-01 2.200e-01 2.900e-01 1.700e-01 5.400e-01
 3.600e-01 3.100e-01 5.200e-01 1.100e-01 1.200e-01 1.100e+00 4.600e-01
 8.000e-02 5.900e-01 2.300e-01 7.800e-01 2.000e-02 8.500e-01 3.400e-01
 2.500e-01 1.800e-01 1.490e+00 1.500e-01 1.300e-01 9.000e-01 4.100e-01
 3.000e-02 3.700e-01 5.000e-02 3.300e-01 4.200e-01 6.000e-02 9.500e-01
 1.230e+00 6.600e-01 4.300e-01 3.500e-01]
JP_Sales : [3.770e+00 6.810e+00 3.790e+00 3.280e+00 1.022e+01 4.220e+00 6.500e+00
 2.930e+00 4.700e+00 2.800e-01 1.930e+00 4.130e+00 7.200e+00 3.600e+00
 2.530e+00 2.400e-01 9.700e-01 4.100e-01 3.540e+00 4.160e+00 6.040e+00
 4.180e+00 3.840e+00 6.000e-02 4.700e-01 5.380e+00 5.650e+00 5.320e+00
 1.870e+00 1.300e-01 3.120e+00 1.100e-01 4.340e+00 3.500e-01 6.500e-01
 7.000e-02 8.000e-02 4.900e-01 3.000e-01 2.660e+00 4.800e-01 5.330e+00
 2.670e+00 3.600e-01 3.960e+00 1.910e+00 1.100e+00 1.200e+00 3.080e+00
 2.690e+00 1.400e-01 2.540e+00 2.130e+00 8.100e-01 3.800e-01 4.400e-01
 2.120e+00 3.150e+00 1.250e+00 0.000e+00 4.000e-02 2.230e+00 2.470e+00
 1.000e-02 1.690e+00 3.000e+00 2.000e-02 4.360e+00 1.980e+00 1.000e-01
 3.810e+00 2.490e+00 5.000e-02 1.580e+00 3.140e+00 6.600e-01 2.730e+00
 3.630e+00 9.800e-01 2.200e-01 1.450e+00 1.310e+00 7.000e-01 2.420e+00
 6.000e-01 1.400e+00 1.420e+00 1.390e+00 1.270e+00 8.700e-01 1.700e-01
 1.900e-01 9.400e-01 2.100e-01 1.600e+00 1.030e+00 2.500e-01 1.600e-01
 2.060e+00 1.490e+00 1.290e+00 9.000e-02 2.870e+00 3.000e-02 8.300e-01
 7.800e-01 2.330e+00 4.350e+00 2.020e+00 1.360e+00 1.810e+00 1.970e+00
 9.100e-01 9.900e-01 9.500e-01 2.000e+00 1.010e+00 2.780e+00 2.110e+00
 1.090e+00 2.000e-01 3.610e+00 1.570e+00 2.200e+00 1.890e+00 1.700e+00
 1.080e+00 1.500e-01 1.110e+00 8.000e-01 2.900e-01 1.540e+00 1.200e-01
 8.900e-01 4.870e+00 1.520e+00 1.320e+00 1.150e+00 1.440e+00 4.100e+00
 4.600e-01 1.050e+00 1.610e+00 2.600e-01 1.380e+00 7.200e-01 6.200e-01
 1.800e-01 5.700e-01 5.800e-01 3.100e-01 1.760e+00 3.700e-01 2.100e+00
 9.000e-01 5.100e-01 6.400e-01 2.460e+00 9.200e-01 1.070e+00 2.620e+00
 1.120e+00 5.400e-01 7.300e-01 2.700e-01 5.900e-01 3.670e+00 5.500e-01
 4.000e-01 1.750e+00 3.440e+00 3.300e-01 2.550e+00 7.400e-01 8.200e-01
 2.320e+00 7.600e-01 7.700e-01 3.180e+00 2.350e+00 3.190e+00 9.300e-01
 8.800e-01 3.030e+00 4.500e-01 1.160e+00 1.190e+00 3.400e-01 1.130e+00
 6.800e-01 1.960e+00 7.100e-01 1.040e+00 2.680e+00 2.650e+00 9.600e-01
 2.410e+00 5.200e-01 2.430e+00 1.340e+00 1.480e+00 2.340e+00 1.060e+00
 1.210e+00 2.280e+00 1.630e+00 2.050e+00 2.170e+00 1.560e+00 1.350e+00
 6.300e-01 7.500e-01 7.900e-01 5.300e-01 1.530e+00 1.300e+00 1.460e+00
 1.330e+00 3.900e-01 6.900e-01 4.200e-01 5.600e-01 8.400e-01 3.200e-01
 1.710e+00 1.650e+00 6.100e-01 1.510e+00 1.500e+00 1.240e+00 1.180e+00
 1.370e+00 1.000e+00 1.260e+00 4.300e-01 8.500e-01 1.280e+00 6.700e-01
 1.140e+00 8.600e-01 1.170e+00 5.000e-01 1.020e+00 2.300e-01]
Other_Sales : [8.460e+00 7.700e-01 3.310e+00 2.960e+00 1.000e+00 5.800e-01 2.900e+00
 2.850e+00 2.260e+00 4.700e-01 2.750e+00 1.920e+00 7.100e-01 2.150e+00
 1.790e+00 1.670e+00 4.140e+00 1.057e+01 5.500e-01 2.050e+00 1.370e+00
 4.200e-01 4.600e-01 1.380e+00 1.780e+00 5.000e-01 8.200e-01 1.180e+00
 1.160e+00 1.320e+00 5.900e-01 1.130e+00 7.900e-01 2.310e+00 2.520e+00

In [163]:
df.value_counts().sum()

16291

In [164]:
df['Platform'].value_counts()

Platform
DS      2163
PS2     2161
PS3     1329
Wii     1325
X360    1265
PSP     1213
PS      1196
PC       960
XB       824
GBA      822
GC       556
3DS      509
PSV      413
PS4      336
N64      319
SNES     239
XOne     213
SAT      173
WiiU     143
2600     133
NES       98
GB        98
DC        52
GEN       27
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

### Convert datatypes
year(float)--> int

In [165]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [166]:
df.dropna(subset=['Year'],inplace=True)

In [167]:
df['Year']=df['Year'].astype(int)

In [168]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year              int32
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

### Checking duplicates

In [169]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
16593    False
16594    False
16595    False
16596    False
16597    False
Length: 16327, dtype: bool

In [170]:
df.duplicated().sum()

0

In [171]:
df.duplicated(subset=['Rank','Genre']).sum()

0

In [172]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [173]:
df.duplicated(subset=['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sum()

0

## Feature Engineering

In [174]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

### calculate the total sales ratio across different regions (North America, Europe, Japan, and others) and store the result in a new column in a DataFrame?

In [175]:
df['Total_sales_ratio']=df['NA_Sales']+df['EU_Sales']+df['JP_Sales']+df['JP_Sales']+df['Other_Sales']/100

In [176]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100

### calculate the age of games in your dataset based on the release year

In [177]:
import datetime

In [178]:
print(datetime.datetime.now())

2024-09-02 23:28:19.493110

In [179]:
df['Game_age']=2024-df['Year']

In [180]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio,Game_age
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346,18
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877,39
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431,16
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496,15
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100,28

## Remove a column

### remove a specific column from a DataFrame in place, without creating a new DataFrame?

In [181]:
df.drop(columns=['Game_age'],inplace=True)

In [182]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100

### Rename()

In [183]:
df.rename(columns={'Name':'Game_Name'},inplace=True)

In [184]:
df.head()

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100

## Filter and sort

 ### Filter games released in a specific year

In [185]:
releasing_year=df[df['Year']==2015]
releasing_year.reset_index(drop=True,inplace=True)
releasing_year

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,34,Call of Duty: Black Ops 3,PS4,2015,Shooter,Activision,5.77,5.81,0.35,2.31,14.24,12.3031
1,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.11,6.06,0.06,1.26,8.49,7.3026
2,93,Star Wars Battlefront (2015),PS4,2015,Shooter,Electronic Arts,2.93,3.29,0.22,1.23,7.67,6.6723
3,102,Call of Duty: Black Ops 3,XOne,2015,Shooter,Activision,4.52,2.09,0.01,0.67,7.30,6.6367
4,110,Fallout 4,PS4,2015,Role-Playing,Bethesda Softworks,2.47,3.15,0.24,1.10,6.96,6.1110
...,...,...,...,...,...,...,...,...,...,...,...,...
609,16502,Irotoridori no Sekai: World's End Re-Birth,PSV,2015,Action,HuneX,0.00,0.00,0.01,0.00,0.01,0.0200
610,16531,Kiniro no Corda 3,3DS,2015,Adventure,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,0.0200
611,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01,0.0200
612,16551,Hakuoki: Reimeiroku - Omouhase Kara,PSV,2015,Action,Idea Factory,0.00,0.00,0.01,0.00,0.01,0.0200
613,16568,Teslagrad,PSV,2015,Platform,Rain Games,0.00,0.01,0.00,0.00,0.01,0.0100

### Filter games from a specific genre

In [186]:
action_game=df[df['Genre'] == 'Action']
action_game.reset_index(drop=True,inplace=True)
action_game.head()

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,17,Grand Theft Auto V,PS3,2013,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,18.2614
1,18,Grand Theft Auto: San Andreas,PS2,2004,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81,10.7557
2,24,Grand Theft Auto V,X360,2013,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38,15.0738
3,25,Grand Theft Auto: Vice City,PS2,2002,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15,14.8578
4,39,Grand Theft Auto III,PS2,2001,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10,12.1130

### Filter games with Global Sales greater than 50 million units

In [187]:
high_sales_game=df[df['Global_Sales']>50]
high_sales_game

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346

### filter and sort the vgsales_online_game dataset to find all games released in 2014, displaying their name, platform, publisher, and total sales ratio, sorted by platform in ascending order and total sales ratio in descending  ?

In [188]:
releasedIn2014=df.loc[df['Year']==2014][['Game_Name','Platform','Publisher','Total_sales_ratio']].sort_values(by=['Platform','Total_sales_ratio'],ascending=[True,False])
releasedIn2014.reset_index(drop=True,inplace=True)
releasedIn2014

,Game_Name,Platform,Publisher,Total_sales_ratio
0,Pokemon Omega Ruby/Pokemon Alpha Sapphire,3DS,Nintendo,13.7665
1,Super Smash Bros. for Wii U and 3DS,3DS,Nintendo,9.4343
2,Monster Hunter 4 Ultimate,3DS,Nintendo,6.4011
3,Yokai Watch 2 Ganso/Honke,3DS,Nintendo,6.3900
4,Yokai Watch 2 Shinuchi,3DS,Level 5,5.3600
...,...,...,...,...
577,Terraria,XOne,505 Games,0.0400
578,Warriors Orochi 3,XOne,Tecmo Koei,0.0400
579,The Golf Club,XOne,Unknown,0.0200
580,Psycho-Pass,XOne,5pb,0.0200
581,Rabbids Invasion: The Interactive TV Show,XOne,Ubisoft,0.0100

### Filter for games by a specific publisher with Global Sales over 1 million units

In [189]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       'Majesco Entertainment', 'Codemasters', 'Red Orb', 'Level 5',
       'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver',
       '989 Studios', 'NCSoft', 'UEP Systems', 'Parker Bros.', 'Maxis',
       'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment',
       'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve',
       'Activision Value', 'Banpresto', 'D3Publisher',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios',
       'GungHo', 'Crave Entertainment', 'Hudson Soft', 'Coleco',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Zoo Games', 'Accolade', 'Sony Online Entertainment', '3DO', 'RTL',
       'Natsume', 'Focus Home Interactive', 'Alchemist', nan,
       'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Success', 'Compile', 'Russel', 'Taito',
       'Agetec', 'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'SCi', 'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft',
       'Square EA', '20th Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis',
       'Big Ben Interactive', 'Touchstone', 'Spike', 'Jester Interactive',
       'Nippon Ichi Software', 'LEGO Media', 'Quest',
       'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute',
       'Rondomedia', 'Sony Computer Entertainment America',
       'Universal Gamex', 'Ghostlight', 'Wizard Video Games',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System 3 Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Rebellion', 'Xplosiv', 'GameMill Entertainment',
       'Wanadoo', 'NovaLogic', 'Telltale Games', 'Epoch',
       'BAM! Entertainment', 'Knowledge Adventure', 'Mastiff',
       'Tetris Online', 'Harmonix Music Systems', 'ESP', 'TYO',
       'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Starfish',
       'Zushi Games', 'Jorudan', 'Destination Software, Inc', 'New',
       'Brash Entertainment', 'ITT Family Games', 'PopCap Games',
       'Home Entertainment Suppliers', 'Ackkstudios', 'Starpath Corp.',
       'P2 Games', 'BPS', 'Gathering of Developers', 'NewKidCo',
       'Storm City Games', 'CokeM Interactive', 'CBS Electronics',
       'Magix', 'Marvelous Interactive', 'Kalypso Media',
       'Nihon Falcom Corporation', 'Wargaming.net', 'Angel Studios',
       'Arc System Works', 'Playmates', 'SNK Playmore',
       'Hamster Corporation', 'From Software', 'Nippon Columbia',
       'Nichibutsu', 'Little Orbit', 'Conspiracy Entertainment',
       'DTP Entertainment', 'Hect', 'Mumbo Jumbo',
       'Pacific Century Cyber Works', 'Indie Games', 'Liquid Games',
       'NEC', 'Axela', 'ArtDink', 'Sunsoft', 'Gust', 'SNK',
       'NEC Interchannel', 'FuRyu', 'Xing Entertainment', 'ValuSoft',
       'Victor Interactive', 'Detn8 Games', 'American Softworks',
       'Nordcurrent', 'Bomb', 'Falcom Corporation', 'AQ Interactive',
       'CCP', 'Milestone S.r.l.', 'JoWood Productions',
       'Seta Corporation', 'On Demand', 'NCS', 'Aspyr',
       'Gremlin Interactive Ltd', 'Agatsuma Entertainment',
       'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan',
       'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet',
       'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon',
       'SSI', 'Kadokawa Games', 'Idea Factory',
       'Performance Designed Products', 'Asylum Entertainment',
       'Core Design Ltd.', 'PlayV', 'UFO Interactive',
       'Idea Factory International', 'Playlogic Game Factory',
       'Essential Games', 'Adeline Software', 'Funcom',
       'Panther Software', 'Blast! Entertainment Ltd', 'Game Life',
       'DSI Games', 'Avalon Interactive', 'Popcorn Arcade',
       'Neko Entertainment', 'Vir2L Studios', 'Aques', 'Syscom',
       'White Park Bay Software', 'System 3', 'Vatical Entertainment',
       'Daedalic', 'EA Games', 'Media Factory', 'Vic Tokai',
       'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire',
       'General Entertainment', 'Excalibur Publishing', 'Imadio',
       'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Paradox Interactive', 'Hip Interactive',
       'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting',
       'Yacht Club Games', 'SCS Software', 'Bigben Interactive',
       'Havas Interactive', 'Slitherine Software', 'Graffiti', 'Funsta',
       'Telstar', 'U.S. Gold', 'DreamWorks Interactive',
       'Data Design Interactive', 'MTO', 'DHM Interactive', 'FunSoft',
       'SPS', 'Bohemia Interactive', 'Reef Entertainment',
       'Tru Blu Entertainment', 'Moss', 'T&E Soft', 'O-Games',
       'Aksys Games', 'NDA Productions', 'Data East',
       'Time Warner Interactive', 'Gainax Network Systems', 'Daito',
       'O3 Entertainment', 'Gameloft', 'Xicat Interactive',
       'Simon & Schuster Interactive', 'Valcon Games', 'PopTop Software',
       'TOHO', 'HMH Interactive', '5pb', 'Cave',
       'CDV Software Entertainment', 'Microids', 'PM Studios', 'Paon',
       'Micro Cabin', 'GameTek', 'Benesse', 'Type-Moon',
       'Enjoy Gaming ltd.', 'Asmik Corp', 'Interplay Productions',
       'Asmik Ace Entertainment', 'inXile Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Culture Publishers', 'Griffin International', 'Hackberry',
       'Hearty Robin', 'Nippon Amuse', 'Origin Systems', 'Seventh Chord',
       'Mitsui', 'Milestone', 'Abylight', 'Flight-Plan', 'Glams', 'Locus',
       'Warp', 'Daedalic Entertainment', 'Alternative Software',
       'Myelin Media', 'Mercury Games', 'Irem Software Engineering',
       'Sunrise Interactive', 'Elite', 'Evolution Games', 'Tivola',
       'Global A Entertainment', 'Edia', 'Athena', 'Aria', 'Gamecock',
       'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works', 'Fortyfive',
       'Revolution Software', 'Imax', 'Crimson Cow', '10TACLE Studios',
       'Groove Games', 'Pack-In-Video', 'Insomniac Games',
       'Ascaron Entertainment GmbH', 'Asgard', 'Ecole', 'Yumedia',
       'Phenomedia', 'HAL Laboratory', 'Grand Prix Games', 'DigiCube',
       'Creative Core', 'Kaga Create', 'WayForward Technologies',
       'LSP Games', 'ASCII Media Works', 'Coconuts Japan', 'Arika',
       'Ertain', 'Marvel Entertainment', 'Prototype', 'Phantagram',
       '1C Company', 'The Learning Company', 'TechnoSoft', 'Vap',
       'Misawa', 'Tradewest', 'Team17 Software', 'Yeti', 'Pow',
       'Navarre Corp', 'MediaQuest', 'Max Five', 'Comfort',
       'Monte Christo Multimedia', 'Pony Canyon', 'Riverhillsoft',
       'Summitsoft', 'Milestone S.r.l', 'Playmore', 'MLB.com',
       'Kool Kizz', 'Flashpoint Games', '49Games', 'Legacy Interactive',
       'Alawar Entertainment', 'CyberFront',
       'Cloud Imperium Games Corporation', 'Societa',
       'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc.',
       'Zenrin', 'Iceberg Interactive', 'Ivolgamus', '2D Boy',
       'MC2 Entertainment', 'Kando Games', 'Just Flight', 'Office Create',
       'Mamba Games', 'Fields', 'Princess Soft', 'Maximum Family Games',
       'Berkeley', 'Fuji', 'Dusenberry Martin Racing', 'imageepoch Inc.',
       'Big Fish Games', 'Her Interactive', 'Kamui', 'ASK',
       'TopWare Interactive', 'Headup Games', 'KSS', 'Cygames', 'KID',
       'Quinrose', 'Sunflowers', 'dramatic create', 'TGL', 'Encore',
       'Extreme Entertainment Group', 'Intergrow', 'G.Rev', 'Sweets',
       'Kokopeli Digital Studios', 'Number None', 'Nexon', 'id Software',
       'BushiRoad', 'Tryfirst', 'Strategy First', '7G//AMES',
       'GN Software', "Yuke's", 'Easy Interactive', 'Licensed 4U',
       'FuRyu Corporation', 'Lexicon Entertainment', 'Paon Corporation',
       'Kids Station', 'GOA', 'Graphsim Entertainment', 'King Records',
       'Introversion Software', 'Minato Station', 'Devolver Digital',
       'Blue Byte', 'Gaga', 'Yamasa Entertainment', 'Plenty', 'Views',
       'fonfun', 'NetRevo', 'Codemasters Online', 'Quintet',
       'Phoenix Games', 'Dorart', 'Marvelous Games', 'Focus Multimedia',
       'Imageworks', 'Karin Entertainment', 'Aerosoft',
       'Technos Japan Corporation', 'Gakken', 'Mirai Shounen',
       'Datam Polystar', 'Saurus', 'HuneX', 'Revolution (Japan)',
       'Giza10', 'Visco', 'Alvion', 'Mycom', 'Giga', 'Warashi',
       'System Soft', 'Sold Out', 'Lighthouse Interactive',
       'Masque Publishing', 'RED Entertainment', 'Michaelsoft',
       'Media Entertainment', 'New World Computing', 'Genterprise',
       'Interworks Unlimited, Inc.', 'Boost On', 'Stainless Games',
       'EON Digital Entertainment', 'Epic Games', 'Naxat Soft',
       'Ascaron Entertainment', 'Piacci', 'Nitroplus',
       'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed',
       'Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Rain Games',
       'UIG Entertainment'], dtype=object)

In [190]:
Imagic_games = df.loc[(df['Publisher'] == 'Imagic') & (df['Global_Sales'] > 1)]
Imagic_games.reset_index(drop=True,inplace=True)
Imagic_games

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,768,Demon Attack,2600,1981,Shooter,Imagic,1.99,0.12,0.0,0.02,2.13,2.1102
1,1558,Atlantis,2600,1981,Shooter,Imagic,1.18,0.08,0.0,0.01,1.27,1.2601
2,1967,Cosmic Ark,2600,1981,Shooter,Imagic,0.99,0.05,0.0,0.01,1.05,1.0401

###  retrieve the first six rows of the DataFrame, selecting the columns from 'Game_Name' to 'Publisher', and then sort these rows by the 'Year' column in descending order

In [191]:
first_five_rows = df.loc[:5,['Game_Name','Platform','Year','Genre','Publisher']].sort_values(by='Year',ascending=False)
first_five_rows.reset_index(drop=True,inplace=True)
first_five_rows

                  Game_Name Platform  Year         Genre Publisher
0         Wii Sports Resort      Wii  2009        Sports  Nintendo
1            Mario Kart Wii      Wii  2008        Racing  Nintendo
2                Wii Sports      Wii  2006        Sports  Nintendo
3  Pokemon Red/Pokemon Blue       GB  1996  Role-Playing  Nintendo
4                    Tetris       GB  1989        Puzzle  Nintendo
5         Super Mario Bros.      NES  1985      Platform  Nintendo

### Select specific rows and columns by index

In [192]:
vgsales_online_game = df.iloc[:10, :4]
vgsales_online_game

   Rank                  Game_Name Platform  Year
0     1                 Wii Sports      Wii  2006
1     2          Super Mario Bros.      NES  1985
2     3             Mario Kart Wii      Wii  2008
3     4          Wii Sports Resort      Wii  2009
4     5   Pokemon Red/Pokemon Blue       GB  1996
5     6                     Tetris       GB  1989
6     7      New Super Mario Bros.       DS  2006
7     8                   Wii Play      Wii  2006
8     9  New Super Mario Bros. Wii      Wii  2009
9    10                  Duck Hunt      NES  1984

### Select the last row

In [193]:
last_row = df.iloc[-1]
last_row

Rank                            16600
Game_Name            Spirits & Spells
Platform                          GBA
Year                             2003
Genre                        Platform
Publisher                     Wanadoo
NA_Sales                         0.01
EU_Sales                          0.0
JP_Sales                          0.0
Other_Sales                       0.0
Global_Sales                     0.01
Total_sales_ratio                0.01
Name: 16597, dtype: object

## Example of Combination of loc and iloc
### Filter sports games and then select the first 5 rows of specific columns ['Name', 'Global_Sales']

In [194]:
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [195]:
Sports_games_filtered = df.loc[df['Genre'] == 'Sports', ['Game_Name', 'Global_Sales']].iloc[:5]
Sports_games_filtered.reset_index(drop=True,inplace=True)
Sports_games_filtered

           Game_Name  Global_Sales
0         Wii Sports         82.74
1  Wii Sports Resort         33.00
2            Wii Fit         22.72
3       Wii Fit Plus         22.00
4            FIFA 16          8.49

### Filter games released in 2010 and belonging to the racing genre

In [196]:
games_2010_racing = df[(df['Year'] == 2010) & (df['Genre'] == 'Racing')]
games_2010_racing.reset_index(drop=True,inplace=True)
games_2010_racing

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,55,Gran Turismo 5,PS3,2010,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77,9.4812
1,523,Need for Speed: Hot Pursuit,PS3,2010,Racing,Electronic Arts,1.05,1.25,0.03,0.48,2.81,2.3648
2,731,Need for Speed: Hot Pursuit,X360,2010,Racing,Electronic Arts,1.03,0.98,0.00,0.21,2.22,2.0121
3,1244,Sonic & Sega All-Stars Racing,Wii,2010,Racing,Sega,0.65,0.71,0.00,0.15,1.51,1.3615
4,1341,Kinect Joy Ride,X360,2010,Racing,Microsoft Game Studios,0.92,0.40,0.00,0.12,1.44,1.3212
5,1438,F1 2010,PS3,2010,Racing,Codemasters,0.25,0.76,0.08,0.27,1.35,1.1727
6,1804,ModNation Racers,PS3,2010,Racing,Sony Computer Entertainment,0.50,0.41,0.06,0.16,1.13,1.0316
7,1890,Sonic & Sega All-Stars Racing,DS,2010,Racing,Sega,0.44,0.54,0.00,0.11,1.09,0.9811
8,1894,Sonic Free Riders,X360,2010,Racing,Sega,0.74,0.26,0.00,0.09,1.09,1.0009
9,2112,Sonic & Sega All-Stars Racing,PS3,2010,Racing,Sega,0.36,0.46,0.00,0.17,0.98,0.8217
10,2347,F1 2010,X360,2010,Racing,Codemasters,0.18,0.59,0.01,0.10,0.89,0.7910
11,2577,Sonic & SEGA All-Stars Racing with Banjo-Kazooie,X360,2010,Racing,Sega,0.37,0.35,0.00,0.07,0.80,0.7207
12,2755,Split/Second,PS3,2010,Racing,Disney Interactive Studios,0.31,0.31,0.01,0.12,0.75,0.6412
13,2777,Blur,PS3,2010,Racing,Activision,0.22,0.37,0.02,0.13,0.74,0.6313
14,3318,Split/Second,X360,2010,Racing,Disney Interactive Studios,0.32,0.23,0.00,0.06,0.61,0.5506
15,3371,Blur,X360,2010,Racing,Activision,0.25,0.28,0.00,0.06,0.60,0.5306
16,3622,Monster Jam: Path of Destruction,Wii,2010,Racing,Activision,0.50,0.02,0.00,0.03,0.56,0.5203
17,3702,ModNation Racers,PSP,2010,Racing,Sony Computer Entertainment,0.11,0.27,0.02,0.14,0.54,0.4214
18,4126,Need for Speed: Hot Pursuit,Wii,2010,Racing,Electronic Arts,0.18,0.24,0.00,0.05,0.48,0.4205
19,5067,Monster Jam: Path of Destruction,DS,2010,Racing,Activision,0.35,0.00,0.00,0.02,0.38,0.3502
20,5073,Need for Speed: Hot Pursuit,PC,2010,Racing,Electronic Arts,0.12,0.20,0.00,0.06,0.38,0.3206
21,6186,Hot Wheels: Track Attack,DS,2010,Racing,THQ,0.18,0.08,0.00,0.02,0.28,0.2602
22,6784,Monster Jam: Path of Destruction,PS3,2010,Racing,Activision,0.21,0.02,0.00,0.02,0.24,0.2302
23,6931,TrackMania: Build to Race,Wii,2010,Racing,Focus Home Interactive,0.10,0.11,0.00,0.03,0.24,0.2103
24,7103,TRON: Evolution - Battle Grids,Wii,2010,Racing,Disney Interactive Studios,0.18,0.03,0.00,0.02,0.23,0.2102
25,7179,MotoGP 09/10,PS3,2010,Racing,Capcom,0.05,0.13,0.00,0.04,0.22,0.1804
26,7293,SBK X: Superbike World Championship,PS3,2010,Racing,Black Bean Games,0.05,0.13,0.00,0.04,0.22,0.1804
27,7640,Hot Wheels: Track Attack,Wii,2010,Racing,THQ,0.15,0.04,0.00,0.01,0.20,0.1901
28,7985,SBK X: Superbike World Championship,X360,2010,Racing,Black Bean Games,0.10,0.07,0.00,0.02,0.19,0.1702
29,8122,World of Outlaws: Sprint Cars,X360,2010,Racing,THQ,0.17,0.00,0.00,0.01,0.18,0.1701
30,8337,MotoGP 09/10,X360,2010,Racing,Capcom,0.07,0.09,0.00,0.02,0.17,0.1602
31,9023,Adrenalin Misfits,X360,2010,Racing,Konami Digital Entertainment,0.12,0.02,0.00,0.01,0.14,0.1401
32,9854,nail'd,PS3,2010,Racing,Deep Silver,0.08,0.02,0.00,0.02,0.12,0.1002
33,9881,Monster Jam: Path of Destruction,X360,2010,Racing,Activision,0.11,0.00,0.00,0.01,0.12,0.1101
34,10076,Blood Drive,X360,2010,Racing,Activision,0.09,0.01,0.00,0.01,0.11,0.1001
35,10184,ATV Quad Kings,DS,2010,Racing,Storm City Games,0.10,0.00,0.00,0.01,0.11,0.1001
36,10213,Split/Second,PSP,2010,Racing,Disney Interactive Studios,0.07,0.02,0.00,0.02,0.11,0.0902
37,10627,nail'd,X360,2010,Racing,Deep Silver,0.08,0.02,0.00,0.01,0.10,0.1001
38,11316,Monster Jam: Path of Destruction,PSP,2010,Racing,Activision,0.07,0.00,0.00,0.01,0.08,0.0701
39,11859,Blood Drive,PS3,2010,Racing,Activision,0.07,0.00,0.00,0.00,0.07,0.0700
40,11891,Speed,Wii,2010,Racing,Unknown,0.04,0.02,0.00,0.01,0.07,0.0601
41,12385,Blur,PC,2010,Racing,Activision,0.01,0.04,0.00,0.01,0.06,0.0501
42,12447,Chevrolet Camaro: Wild Ride,Wii,2010,Racing,Storm City Games,0.06,0.00,0.00,0.00,0.06,0.0600
43,12764,F1 2010,PC,2010,Racing,Codemasters,0.00,0.05,0.00,0.01,0.06,0.0501
44,12926,TrackMania Turbo: Build to Race,DS,2010,Racing,Ubisoft,0.03,0.02,0.00,0.01,0.05,0.0501
45,13314,Forza Motorsport 3: Ultimate Edition,X360,2010,Racing,Microsoft Game Studios,0.00,0.04,0.00,0.01,0.05,0.0401
46,13345,Galaxy Racers,DS,2010,Racing,Ubisoft,0.04,0.00,0.00,0.00,0.05,0.0400
47,13487,Honda ATV Fever,Wii,2010,Racing,Storm City Games,0.04,0.00,0.00,0.00,0.04,0.0400
48,13539,Split/Second,PC,2010,Racing,Disney Interactive Studios,0.00,0.04,0.00,0.01,0.04,0.0401
49,13730,Harley-Davidson: Road Trip,Wii,2010,Racing,Destineer,0.04,0.00,0.00,0.00,0.04,0.0400
50,14137,Maximum Racing: Drag & Stock Racer,Wii,2010,Racing,Nordic Games,0.03,0.00,0.00,0.00,0.03,0.0300
51,14245,Maximum Racing: GP Classic Racing,Wii,2010,Racing,Nordic Games,0.03,0.00,0.00,0.00,0.03,0.0300
52,14561,Heathcliff! The Fast and the Furriest,Wii,2010,Racing,Storm City Games,0.03,0.00,0.00,0.00,0.03,0.0300
53,15379,Chevrolet Camaro: Wild Ride,DS,2010,Racing,Storm City Games,0.02,0.00,0.00,0.00,0.02,0.0200
54,15410,Maximum Racing: Crash Car Racer,Wii,2010,Racing,Nordic Games,0.01,0.01,0.00,0.00,0.02,0.0200
55,15887,GTI Club: Supermini Festa!,Wii,2010,Racing,Konami Digital Entertainment,0.01,0.00,0.00,0.00,0.02,0.0100
56,16093,Honda ATV Fever,DS,2010,Racing,Storm City Games,0.01,0.00,0.00,0.00,0.01,0.0100

### Filter games with Global Sales over 10 million units in either Europe or Japan

In [197]:
high_sales_eu_jp = df[(df['EU_Sales'] > 10) | (df['JP_Sales'] > 10)]
high_sales_eu_jp.reset_index(drop=True,inplace=True)
high_sales_eu_jp

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346
1,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431
2,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496
3,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100
4,11,Nintendogs,DS,2005,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76,23.9575

### filter the vgsales_online_game dataset to find all games with 'Kids' in their title?

In [198]:
kids=df[df['Game_Name'].str.contains('Kids')]
kids

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
682,684,Just Dance Kids,Wii,2010,Misc,Ubisoft,1.57,0.56,0.00,0.19,2.32,2.1319
4407,4409,Discovery Kids: Kitten Corner,DS,2009,Simulation,505 Games,0.42,0.00,0.00,0.03,0.45,0.4203
4761,4763,Just Dance Kids 2,X360,2011,Misc,Ubisoft,0.29,0.09,0.00,0.03,0.41,0.3803
5534,5536,Spy Kids 3-D: Game Over,GBA,2003,Platform,Disney Interactive Studios,0.24,0.09,0.00,0.01,0.33,0.3301
5566,5568,Discovery Kids: Puppy Playtime,DS,2009,Simulation,505 Games,0.30,0.00,0.00,0.02,0.33,0.3002
5955,5957,Just Dance Kids 2,Wii,2011,Misc,Ubisoft,0.28,0.00,0.00,0.02,0.29,0.2802
6639,6641,Spy Kids Challenger,GBA,2002,Platform,Disney Interactive Studios,0.18,0.07,0.00,0.00,0.25,0.2500
6660,6662,Just Dance Kids 2,PS3,2011,Misc,Ubisoft,0.10,0.10,0.00,0.04,0.25,0.2004
7021,7023,Virtua Fighter Kids,SAT,1995,Fighting,Sega,0.00,0.00,0.23,0.00,0.23,0.4600
7162,7164,Discovery Kids: Dolphin Discovery,DS,2008,Simulation,505 Games,0.21,0.00,0.00,0.01,0.22,0.2101
7499,7501,Discovery Kids: Pony Paradise,DS,2009,Simulation,505 Games,0.19,0.00,0.00,0.01,0.20,0.1901
7624,7626,Snowboard Kids,N64,1996,Sports,Atlus,0.16,0.04,0.00,0.00,0.20,0.2000
8004,8006,Sports Illustrated for Kids: Football,GBA,2003,Sports,BAM! Entertainment,0.13,0.05,0.00,0.00,0.18,0.1800
8225,8227,Sports Illustrated for Kids: Baseball,GBA,2001,Sports,BAM! Entertainment,0.12,0.05,0.00,0.00,0.17,0.1700
8341,8343,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004,Misc,NaN,0.12,0.05,0.00,0.00,0.17,0.1700
8825,8827,Kids Learn Math: A+ Edition,DS,2011,Misc,Unknown,0.14,0.00,0.00,0.01,0.15,0.1401
10216,10218,Snowboard Kids 2,N64,1999,Sports,Atlus,0.09,0.02,0.00,0.00,0.11,0.1100
10312,10314,FoxKids.com Micro Maniacs Racing,PS,2000,Racing,Codemasters,0.06,0.04,0.00,0.01,0.11,0.1001
10617,10619,Codename: Kids Next Door: Operation V.I.D.E.O....,PS2,2005,Platform,Global Star,0.05,0.04,0.00,0.01,0.10,0.0901
11556,11558,Discovery Kids: Spider Quest,DS,2009,Misc,505 Games,0.07,0.00,0.00,0.01,0.08,0.0701
11708,11710,Codename: Kids Next Door: Operation S.O.D.A.,GBA,2004,Platform,Global Star,0.05,0.02,0.00,0.00,0.08,0.0700
11861,11863,Discovery Kids: Parrot Pals,DS,2009,Simulation,505 Games,0.07,0.00,0.00,0.00,0.07,0.0700
13069,13071,Kids Learn Music A+ Edition,DS,2011,Misc,Unknown,0.05,0.00,0.00,0.00,0.05,0.0500
13150,13152,Codename: Kids Next Door: Operation V.I.D.E.O....,GC,2005,Platform,Global Star,0.04,0.01,0.00,0.00,0.05,0.0500
13337,13339,Clever Kids: Creepy Crawlies,DS,2009,Action,Midas Interactive Entertainment,0.00,0.04,0.00,0.00,0.05,0.0400
14140,14142,Clever Kids: Pirates,DS,2008,Misc,Midas Interactive Entertainment,0.00,0.03,0.00,0.00,0.03,0.0300
15060,15063,DemiKids: Dark Version,GBA,2002,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
15066,15069,DemiKids: Light Version,GBA,2002,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
15158,15161,SBK: Snowboard Kids,DS,2005,Sports,Rising Star Games,0.02,0.00,0.00,0.00,0.02,0.0200
15239,15242,Discovery Kids: Snake Safari,DS,2009,Simulation,505 Games,0.02,0.00,0.00,0.00,0.02,0.0200
15487,15490,Codename: Kids Next Door: Operation V.I.D.E.O....,XB,2005,Platform,Global Star,0.01,0.00,0.00,0.00,0.02,0.0100
15704,15707,Cabbage Patch Kids: The Patch Puppy Rescue,GBA,2007,Misc,D3Publisher,0.01,0.00,0.00,0.00,0.02,0.0100
16414,16417,thinkSMART: Chess for Kids,DS,2011,Misc,Mentor Interactive,0.01,0.00,0.00,0.00,0.01,0.0100

### filter the DataFrame to display only the rows where the 'Game_Name' column contains the word 'Women

In [199]:
Women=df[df['Game_Name'].str.contains('Women')]
Women.reset_index(drop=True,inplace=True)
Women

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,4705,James Patterson Women's Murder Club: Games of ...,DS,2009,Adventure,THQ,0.15,0.22,0.00,0.05,0.41,0.3705
1,14182,Women's Volleyball Championship,PS2,2007,Sports,Spike,0.00,0.00,0.03,0.00,0.03,0.0600

## isin()
###  filter the dataset to find all games published by 'Inti Creates', 'Takuyo', 'Interchannel-Holon', or 'Rain Games'?

In [200]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       'Majesco Entertainment', 'Codemasters', 'Red Orb', 'Level 5',
       'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver',
       '989 Studios', 'NCSoft', 'UEP Systems', 'Parker Bros.', 'Maxis',
       'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment',
       'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve',
       'Activision Value', 'Banpresto', 'D3Publisher',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios',
       'GungHo', 'Crave Entertainment', 'Hudson Soft', 'Coleco',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Zoo Games', 'Accolade', 'Sony Online Entertainment', '3DO', 'RTL',
       'Natsume', 'Focus Home Interactive', 'Alchemist', nan,
       'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Success', 'Compile', 'Russel', 'Taito',
       'Agetec', 'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'SCi', 'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft',
       'Square EA', '20th Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis',
       'Big Ben Interactive', 'Touchstone', 'Spike', 'Jester Interactive',
       'Nippon Ichi Software', 'LEGO Media', 'Quest',
       'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute',
       'Rondomedia', 'Sony Computer Entertainment America',
       'Universal Gamex', 'Ghostlight', 'Wizard Video Games',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System 3 Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Rebellion', 'Xplosiv', 'GameMill Entertainment',
       'Wanadoo', 'NovaLogic', 'Telltale Games', 'Epoch',
       'BAM! Entertainment', 'Knowledge Adventure', 'Mastiff',
       'Tetris Online', 'Harmonix Music Systems', 'ESP', 'TYO',
       'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Starfish',
       'Zushi Games', 'Jorudan', 'Destination Software, Inc', 'New',
       'Brash Entertainment', 'ITT Family Games', 'PopCap Games',
       'Home Entertainment Suppliers', 'Ackkstudios', 'Starpath Corp.',
       'P2 Games', 'BPS', 'Gathering of Developers', 'NewKidCo',
       'Storm City Games', 'CokeM Interactive', 'CBS Electronics',
       'Magix', 'Marvelous Interactive', 'Kalypso Media',
       'Nihon Falcom Corporation', 'Wargaming.net', 'Angel Studios',
       'Arc System Works', 'Playmates', 'SNK Playmore',
       'Hamster Corporation', 'From Software', 'Nippon Columbia',
       'Nichibutsu', 'Little Orbit', 'Conspiracy Entertainment',
       'DTP Entertainment', 'Hect', 'Mumbo Jumbo',
       'Pacific Century Cyber Works', 'Indie Games', 'Liquid Games',
       'NEC', 'Axela', 'ArtDink', 'Sunsoft', 'Gust', 'SNK',
       'NEC Interchannel', 'FuRyu', 'Xing Entertainment', 'ValuSoft',
       'Victor Interactive', 'Detn8 Games', 'American Softworks',
       'Nordcurrent', 'Bomb', 'Falcom Corporation', 'AQ Interactive',
       'CCP', 'Milestone S.r.l.', 'JoWood Productions',
       'Seta Corporation', 'On Demand', 'NCS', 'Aspyr',
       'Gremlin Interactive Ltd', 'Agatsuma Entertainment',
       'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan',
       'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet',
       'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon',
       'SSI', 'Kadokawa Games', 'Idea Factory',
       'Performance Designed Products', 'Asylum Entertainment',
       'Core Design Ltd.', 'PlayV', 'UFO Interactive',
       'Idea Factory International', 'Playlogic Game Factory',
       'Essential Games', 'Adeline Software', 'Funcom',
       'Panther Software', 'Blast! Entertainment Ltd', 'Game Life',
       'DSI Games', 'Avalon Interactive', 'Popcorn Arcade',
       'Neko Entertainment', 'Vir2L Studios', 'Aques', 'Syscom',
       'White Park Bay Software', 'System 3', 'Vatical Entertainment',
       'Daedalic', 'EA Games', 'Media Factory', 'Vic Tokai',
       'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire',
       'General Entertainment', 'Excalibur Publishing', 'Imadio',
       'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Paradox Interactive', 'Hip Interactive',
       'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting',
       'Yacht Club Games', 'SCS Software', 'Bigben Interactive',
       'Havas Interactive', 'Slitherine Software', 'Graffiti', 'Funsta',
       'Telstar', 'U.S. Gold', 'DreamWorks Interactive',
       'Data Design Interactive', 'MTO', 'DHM Interactive', 'FunSoft',
       'SPS', 'Bohemia Interactive', 'Reef Entertainment',
       'Tru Blu Entertainment', 'Moss', 'T&E Soft', 'O-Games',
       'Aksys Games', 'NDA Productions', 'Data East',
       'Time Warner Interactive', 'Gainax Network Systems', 'Daito',
       'O3 Entertainment', 'Gameloft', 'Xicat Interactive',
       'Simon & Schuster Interactive', 'Valcon Games', 'PopTop Software',
       'TOHO', 'HMH Interactive', '5pb', 'Cave',
       'CDV Software Entertainment', 'Microids', 'PM Studios', 'Paon',
       'Micro Cabin', 'GameTek', 'Benesse', 'Type-Moon',
       'Enjoy Gaming ltd.', 'Asmik Corp', 'Interplay Productions',
       'Asmik Ace Entertainment', 'inXile Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Culture Publishers', 'Griffin International', 'Hackberry',
       'Hearty Robin', 'Nippon Amuse', 'Origin Systems', 'Seventh Chord',
       'Mitsui', 'Milestone', 'Abylight', 'Flight-Plan', 'Glams', 'Locus',
       'Warp', 'Daedalic Entertainment', 'Alternative Software',
       'Myelin Media', 'Mercury Games', 'Irem Software Engineering',
       'Sunrise Interactive', 'Elite', 'Evolution Games', 'Tivola',
       'Global A Entertainment', 'Edia', 'Athena', 'Aria', 'Gamecock',
       'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works', 'Fortyfive',
       'Revolution Software', 'Imax', 'Crimson Cow', '10TACLE Studios',
       'Groove Games', 'Pack-In-Video', 'Insomniac Games',
       'Ascaron Entertainment GmbH', 'Asgard', 'Ecole', 'Yumedia',
       'Phenomedia', 'HAL Laboratory', 'Grand Prix Games', 'DigiCube',
       'Creative Core', 'Kaga Create', 'WayForward Technologies',
       'LSP Games', 'ASCII Media Works', 'Coconuts Japan', 'Arika',
       'Ertain', 'Marvel Entertainment', 'Prototype', 'Phantagram',
       '1C Company', 'The Learning Company', 'TechnoSoft', 'Vap',
       'Misawa', 'Tradewest', 'Team17 Software', 'Yeti', 'Pow',
       'Navarre Corp', 'MediaQuest', 'Max Five', 'Comfort',
       'Monte Christo Multimedia', 'Pony Canyon', 'Riverhillsoft',
       'Summitsoft', 'Milestone S.r.l', 'Playmore', 'MLB.com',
       'Kool Kizz', 'Flashpoint Games', '49Games', 'Legacy Interactive',
       'Alawar Entertainment', 'CyberFront',
       'Cloud Imperium Games Corporation', 'Societa',
       'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc.',
       'Zenrin', 'Iceberg Interactive', 'Ivolgamus', '2D Boy',
       'MC2 Entertainment', 'Kando Games', 'Just Flight', 'Office Create',
       'Mamba Games', 'Fields', 'Princess Soft', 'Maximum Family Games',
       'Berkeley', 'Fuji', 'Dusenberry Martin Racing', 'imageepoch Inc.',
       'Big Fish Games', 'Her Interactive', 'Kamui', 'ASK',
       'TopWare Interactive', 'Headup Games', 'KSS', 'Cygames', 'KID',
       'Quinrose', 'Sunflowers', 'dramatic create', 'TGL', 'Encore',
       'Extreme Entertainment Group', 'Intergrow', 'G.Rev', 'Sweets',
       'Kokopeli Digital Studios', 'Number None', 'Nexon', 'id Software',
       'BushiRoad', 'Tryfirst', 'Strategy First', '7G//AMES',
       'GN Software', "Yuke's", 'Easy Interactive', 'Licensed 4U',
       'FuRyu Corporation', 'Lexicon Entertainment', 'Paon Corporation',
       'Kids Station', 'GOA', 'Graphsim Entertainment', 'King Records',
       'Introversion Software', 'Minato Station', 'Devolver Digital',
       'Blue Byte', 'Gaga', 'Yamasa Entertainment', 'Plenty', 'Views',
       'fonfun', 'NetRevo', 'Codemasters Online', 'Quintet',
       'Phoenix Games', 'Dorart', 'Marvelous Games', 'Focus Multimedia',
       'Imageworks', 'Karin Entertainment', 'Aerosoft',
       'Technos Japan Corporation', 'Gakken', 'Mirai Shounen',
       'Datam Polystar', 'Saurus', 'HuneX', 'Revolution (Japan)',
       'Giza10', 'Visco', 'Alvion', 'Mycom', 'Giga', 'Warashi',
       'System Soft', 'Sold Out', 'Lighthouse Interactive',
       'Masque Publishing', 'RED Entertainment', 'Michaelsoft',
       'Media Entertainment', 'New World Computing', 'Genterprise',
       'Interworks Unlimited, Inc.', 'Boost On', 'Stainless Games',
       'EON Digital Entertainment', 'Epic Games', 'Naxat Soft',
       'Ascaron Entertainment', 'Piacci', 'Nitroplus',
       'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed',
       'Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Rain Games',
       'UIG Entertainment'], dtype=object)

In [201]:
games = df[df['Publisher'].isin(['Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Rain Games'])]
games.reset_index(drop=True,inplace=True)
games

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,16475,Azure Striker Gunvolt: Striker Pack,3DS,2016,Action,Inti Creates,0.0,0.00,0.01,0.0,0.01,0.02
1,16506,Shinigami to Shoujo,PSP,2011,Adventure,Takuyo,0.0,0.00,0.01,0.0,0.01,0.02
2,16513,Palais de Reine,PS2,2007,Strategy,Interchannel-Holon,0.0,0.00,0.01,0.0,0.01,0.02
3,16568,Teslagrad,PSV,2015,Platform,Rain Games,0.0,0.01,0.00,0.0,0.01,0.01

In [202]:
df['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

### create a new DataFrame that excludes all rows where the 'Platform' column contains any of the values 'PS', 'PS2', 'PS3', or 'PS4'

In [203]:
excluded_codes=['PS','PS2','PS3','PS4']

In [204]:
other_platform=df[~df['Platform'].isin(excluded_codes)]
other_platform.reset_index(drop=True,inplace=True)
other_platform

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100
...,...,...,...,...,...,...,...,...,...,...,...,...
11366,16595,Plushees,DS,2008,Simulation,Destineer,0.01,0.00,0.00,0.00,0.01,0.0100
11367,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.0100
11368,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.0100
11369,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.0100
11370,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.0100

### Reset_index()

In [205]:
kids.reset_index(drop=True,inplace=True)
kids

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
0,684,Just Dance Kids,Wii,2010,Misc,Ubisoft,1.57,0.56,0.00,0.19,2.32,2.1319
1,4409,Discovery Kids: Kitten Corner,DS,2009,Simulation,505 Games,0.42,0.00,0.00,0.03,0.45,0.4203
2,4763,Just Dance Kids 2,X360,2011,Misc,Ubisoft,0.29,0.09,0.00,0.03,0.41,0.3803
3,5536,Spy Kids 3-D: Game Over,GBA,2003,Platform,Disney Interactive Studios,0.24,0.09,0.00,0.01,0.33,0.3301
4,5568,Discovery Kids: Puppy Playtime,DS,2009,Simulation,505 Games,0.30,0.00,0.00,0.02,0.33,0.3002
5,5957,Just Dance Kids 2,Wii,2011,Misc,Ubisoft,0.28,0.00,0.00,0.02,0.29,0.2802
6,6641,Spy Kids Challenger,GBA,2002,Platform,Disney Interactive Studios,0.18,0.07,0.00,0.00,0.25,0.2500
7,6662,Just Dance Kids 2,PS3,2011,Misc,Ubisoft,0.10,0.10,0.00,0.04,0.25,0.2004
8,7023,Virtua Fighter Kids,SAT,1995,Fighting,Sega,0.00,0.00,0.23,0.00,0.23,0.4600
9,7164,Discovery Kids: Dolphin Discovery,DS,2008,Simulation,505 Games,0.21,0.00,0.00,0.01,0.22,0.2101
10,7501,Discovery Kids: Pony Paradise,DS,2009,Simulation,505 Games,0.19,0.00,0.00,0.01,0.20,0.1901
11,7626,Snowboard Kids,N64,1996,Sports,Atlus,0.16,0.04,0.00,0.00,0.20,0.2000
12,8006,Sports Illustrated for Kids: Football,GBA,2003,Sports,BAM! Entertainment,0.13,0.05,0.00,0.00,0.18,0.1800
13,8227,Sports Illustrated for Kids: Baseball,GBA,2001,Sports,BAM! Entertainment,0.12,0.05,0.00,0.00,0.17,0.1700
14,8343,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004,Misc,NaN,0.12,0.05,0.00,0.00,0.17,0.1700
15,8827,Kids Learn Math: A+ Edition,DS,2011,Misc,Unknown,0.14,0.00,0.00,0.01,0.15,0.1401
16,10218,Snowboard Kids 2,N64,1999,Sports,Atlus,0.09,0.02,0.00,0.00,0.11,0.1100
17,10314,FoxKids.com Micro Maniacs Racing,PS,2000,Racing,Codemasters,0.06,0.04,0.00,0.01,0.11,0.1001
18,10619,Codename: Kids Next Door: Operation V.I.D.E.O....,PS2,2005,Platform,Global Star,0.05,0.04,0.00,0.01,0.10,0.0901
19,11558,Discovery Kids: Spider Quest,DS,2009,Misc,505 Games,0.07,0.00,0.00,0.01,0.08,0.0701
20,11710,Codename: Kids Next Door: Operation S.O.D.A.,GBA,2004,Platform,Global Star,0.05,0.02,0.00,0.00,0.08,0.0700
21,11863,Discovery Kids: Parrot Pals,DS,2009,Simulation,505 Games,0.07,0.00,0.00,0.00,0.07,0.0700
22,13071,Kids Learn Music A+ Edition,DS,2011,Misc,Unknown,0.05,0.00,0.00,0.00,0.05,0.0500
23,13152,Codename: Kids Next Door: Operation V.I.D.E.O....,GC,2005,Platform,Global Star,0.04,0.01,0.00,0.00,0.05,0.0500
24,13339,Clever Kids: Creepy Crawlies,DS,2009,Action,Midas Interactive Entertainment,0.00,0.04,0.00,0.00,0.05,0.0400
25,14142,Clever Kids: Pirates,DS,2008,Misc,Midas Interactive Entertainment,0.00,0.03,0.00,0.00,0.03,0.0300
26,15063,DemiKids: Dark Version,GBA,2002,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
27,15069,DemiKids: Light Version,GBA,2002,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
28,15161,SBK: Snowboard Kids,DS,2005,Sports,Rising Star Games,0.02,0.00,0.00,0.00,0.02,0.0200
29,15242,Discovery Kids: Snake Safari,DS,2009,Simulation,505 Games,0.02,0.00,0.00,0.00,0.02,0.0200
30,15490,Codename: Kids Next Door: Operation V.I.D.E.O....,XB,2005,Platform,Global Star,0.01,0.00,0.00,0.00,0.02,0.0100
31,15707,Cabbage Patch Kids: The Patch Puppy Rescue,GBA,2007,Misc,D3Publisher,0.01,0.00,0.00,0.00,0.02,0.0100
32,16417,thinkSMART: Chess for Kids,DS,2011,Misc,Mentor Interactive,0.01,0.00,0.00,0.00,0.01,0.0100

### Set_index()

In [206]:
kids.set_index(['Year'])

,Rank,Game_Name,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio
Year,,,,,,,,,,,
2010,684,Just Dance Kids,Wii,Misc,Ubisoft,1.57,0.56,0.00,0.19,2.32,2.1319
2009,4409,Discovery Kids: Kitten Corner,DS,Simulation,505 Games,0.42,0.00,0.00,0.03,0.45,0.4203
2011,4763,Just Dance Kids 2,X360,Misc,Ubisoft,0.29,0.09,0.00,0.03,0.41,0.3803
2003,5536,Spy Kids 3-D: Game Over,GBA,Platform,Disney Interactive Studios,0.24,0.09,0.00,0.01,0.33,0.3301
2009,5568,Discovery Kids: Puppy Playtime,DS,Simulation,505 Games,0.30,0.00,0.00,0.02,0.33,0.3002
2011,5957,Just Dance Kids 2,Wii,Misc,Ubisoft,0.28,0.00,0.00,0.02,0.29,0.2802
2002,6641,Spy Kids Challenger,GBA,Platform,Disney Interactive Studios,0.18,0.07,0.00,0.00,0.25,0.2500
2011,6662,Just Dance Kids 2,PS3,Misc,Ubisoft,0.10,0.10,0.00,0.04,0.25,0.2004
1995,7023,Virtua Fighter Kids,SAT,Fighting,Sega,0.00,0.00,0.23,0.00,0.23,0.4600
2008,7164,Discovery Kids: Dolphin Discovery,DS,Simulation,505 Games,0.21,0.00,0.00,0.01,0.22,0.2101
2009,7501,Discovery Kids: Pony Paradise,DS,Simulation,505 Games,0.19,0.00,0.00,0.01,0.20,0.1901
1996,7626,Snowboard Kids,N64,Sports,Atlus,0.16,0.04,0.00,0.00,0.20,0.2000
2003,8006,Sports Illustrated for Kids: Football,GBA,Sports,BAM! Entertainment,0.13,0.05,0.00,0.00,0.18,0.1800
2001,8227,Sports Illustrated for Kids: Baseball,GBA,Sports,BAM! Entertainment,0.12,0.05,0.00,0.00,0.17,0.1700
2004,8343,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,Misc,NaN,0.12,0.05,0.00,0.00,0.17,0.1700
2011,8827,Kids Learn Math: A+ Edition,DS,Misc,Unknown,0.14,0.00,0.00,0.01,0.15,0.1401
1999,10218,Snowboard Kids 2,N64,Sports,Atlus,0.09,0.02,0.00,0.00,0.11,0.1100
2000,10314,FoxKids.com Micro Maniacs Racing,PS,Racing,Codemasters,0.06,0.04,0.00,0.01,0.11,0.1001
2005,10619,Codename: Kids Next Door: Operation V.I.D.E.O....,PS2,Platform,Global Star,0.05,0.04,0.00,0.01,0.10,0.0901
2009,11558,Discovery Kids: Spider Quest,DS,Misc,505 Games,0.07,0.00,0.00,0.01,0.08,0.0701
2004,11710,Codename: Kids Next Door: Operation S.O.D.A.,GBA,Platform,Global Star,0.05,0.02,0.00,0.00,0.08,0.0700
2009,11863,Discovery Kids: Parrot Pals,DS,Simulation,505 Games,0.07,0.00,0.00,0.00,0.07,0.0700
2011,13071,Kids Learn Music A+ Edition,DS,Misc,Unknown,0.05,0.00,0.00,0.00,0.05,0.0500
2005,13152,Codename: Kids Next Door: Operation V.I.D.E.O....,GC,Platform,Global Star,0.04,0.01,0.00,0.00,0.05,0.0500
2009,13339,Clever Kids: Creepy Crawlies,DS,Action,Midas Interactive Entertainment,0.00,0.04,0.00,0.00,0.05,0.0400
2008,14142,Clever Kids: Pirates,DS,Misc,Midas Interactive Entertainment,0.00,0.03,0.00,0.00,0.03,0.0300
2002,15063,DemiKids: Dark Version,GBA,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
2002,15069,DemiKids: Light Version,GBA,Role-Playing,Atlus,0.02,0.01,0.00,0.00,0.02,0.0300
2005,15161,SBK: Snowboard Kids,DS,Sports,Rising Star Games,0.02,0.00,0.00,0.00,0.02,0.0200
2009,15242,Discovery Kids: Snake Safari,DS,Simulation,505 Games,0.02,0.00,0.00,0.00,0.02,0.0200
2005,15490,Codename: Kids Next Door: Operation V.I.D.E.O....,XB,Platform,Global Star,0.01,0.00,0.00,0.00,0.02,0.0100
2007,15707,Cabbage Patch Kids: The Patch Puppy Rescue,GBA,Misc,D3Publisher,0.01,0.00,0.00,0.00,0.02,0.0100
2011,16417,thinkSMART: Chess for Kids,DS,Misc,Mentor Interactive,0.01,0.00,0.00,0.00,0.01,0.0100

## pivot_table()

### create a pivot table that shows the sum of global sales for each genre across different years?

In [207]:
pivot= df.pivot_table(index='Year', columns='Genre', values='Global_Sales',aggfunc='sum')
pivot

Genre,Action,Adventure,Fighting,Misc,Platform,Puzzle,Racing,Role-Playing,Shooter,Simulation,Sports,Strategy
Year,,,,,,,,,,,,
1980,0.34,NaN,0.77,2.71,NaN,NaN,NaN,NaN,7.07,NaN,0.49,NaN
1981,14.84,NaN,NaN,NaN,6.93,2.24,0.48,NaN,10.04,0.45,0.79,NaN
1982,6.52,NaN,NaN,0.87,5.03,10.03,1.57,NaN,3.79,NaN,1.05,NaN
1983,2.86,0.40,NaN,2.14,6.93,0.78,NaN,NaN,0.48,NaN,3.20,NaN
1984,1.85,NaN,NaN,1.45,0.69,3.14,5.95,NaN,31.10,NaN,6.18,NaN
1985,3.52,NaN,1.05,NaN,43.17,3.21,NaN,NaN,1.00,0.03,1.96,NaN
1986,13.74,NaN,NaN,NaN,9.39,NaN,1.96,2.52,3.89,NaN,5.57,NaN
1987,1.12,4.38,5.42,NaN,1.74,NaN,NaN,4.65,0.71,NaN,3.72,NaN
1988,1.75,NaN,NaN,NaN,27.73,5.58,2.14,5.88,0.51,0.03,3.60,NaN
1989,4.64,NaN,NaN,1.28,20.66,37.75,NaN,2.20,1.20,NaN,5.72,NaN
1990,6.39,NaN,NaN,NaN,22.97,6.00,6.26,4.52,NaN,1.14,2.11,NaN
1991,6.76,2.24,0.39,0.08,7.64,3.24,1.14,3.25,2.00,2.14,2.41,0.94
1992,3.83,12.24,15.25,4.94,13.42,4.84,9.04,6.86,0.29,2.14,2.95,0.36
1993,1.81,0.07,8.75,0.30,18.67,3.17,0.36,5.59,3.08,0.19,3.18,0.81
1994,1.55,3.74,8.47,2.86,28.74,1.53,2.19,7.11,8.30,2.73,8.39,3.56
1995,3.57,0.72,14.85,6.40,16.69,2.71,6.09,14.26,4.15,4.18,7.98,6.51
1996,20.58,4.19,18.06,10.68,28.23,3.91,28.24,43.96,6.91,11.33,17.45,5.61
1997,27.58,4.96,11.76,5.69,21.85,5.89,31.91,21.79,22.17,9.65,30.02,7.71
1998,39.44,9.05,31.66,11.94,29.88,6.34,27.90,28.09,9.80,7.11,41.79,13.47
1999,27.78,7.60,14.26,20.65,20.82,1.36,37.27,49.09,12.25,11.44,30.29,18.46
2000,34.04,2.98,20.22,15.54,16.06,3.82,19.99,29.03,6.81,3.38,41.19,8.50
2001,59.39,9.12,18.12,16.40,39.28,8.00,55.81,22.06,24.77,19.54,51.43,7.55
2002,86.77,11.05,25.02,15.67,45.97,5.34,30.20,45.13,48.58,10.81,65.42,5.56
2003,67.93,2.14,23.73,23.82,42.89,2.42,52.19,30.28,27.14,21.21,56.11,7.99
2004,76.26,8.70,16.78,31.32,47.34,8.43,47.86,53.95,46.95,10.85,63.68,7.19
2005,85.69,8.53,19.72,61.24,23.56,20.45,56.42,28.55,41.60,49.27,59.54,5.37
2006,66.58,11.47,22.55,67.35,49.80,10.90,34.09,57.73,38.37,21.77,136.16,4.27
2007,106.50,24.47,17.61,92.27,35.59,24.00,39.17,43.89,71.04,48.97,98.20,9.42
2008,136.39,25.02,35.38,87.03,35.70,15.59,70.66,59.83,59.51,46.76,95.34,11.69
2009,139.36,20.68,32.15,76.94,41.09,20.31,34.19,47.90,69.89,33.71,138.52,12.56
2010,117.64,16.57,14.89,96.86,31.90,11.18,34.93,70.52,77.41,22.15,92.53,13.87
2011,118.96,15.98,22.68,56.08,28.11,5.11,35.01,53.37,99.36,15.28,56.99,9.06
2012,122.04,5.99,9.51,22.92,18.55,1.76,14.46,47.81,72.86,13.38,30.93,3.33
2013,125.22,6.61,7.21,25.65,25.12,0.99,13.04,44.92,62.80,8.67,41.55,6.33
2014,99.02,6.06,16.15,23.68,8.89,1.50,16.69,45.86,66.00,5.55,46.66,0.99
2015,70.70,8.03,7.78,11.69,6.05,0.70,7.92,36.44,66.15,5.62,41.54,1.82
2016,19.91,1.81,3.86,1.17,2.07,NaN,1.64,6.76,18.22,0.39,14.60,0.50
2017,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.04,NaN,NaN,NaN,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.29,NaN,NaN

## Remove warnings

In [208]:
import warnings
warnings.filterwarnings('ignore')

## groupby()

### group the dataset by both game name and year, and then calculate the maximum total sales ratio and minimum global sales for each game in each year?

In [209]:
gr=df.groupby(['Game_Name','Year']).agg({'Total_sales_ratio':max,'Global_Sales':min})
gr

                                              Total_sales_ratio  Global_Sales
Game_Name                               Year
'98 Koshien                             1998             0.4903          0.41
.hack//G.U. Vol.1//Rebirth              2006             0.3400          0.17
.hack//G.U. Vol.2//Reminisce            2006             0.2003          0.23
.hack//G.U. Vol.2//Reminisce (jp sales) 2006             0.3200          0.16
.hack//G.U. Vol.3//Redemption           2007             0.3400          0.17
...                                                         ...           ...
thinkSMART FAMILY!                      2010             0.0300          0.03
thinkSMART: Chess for Kids              2011             0.0100          0.01
uDraw Studio                            2010             2.2520          2.46
uDraw Studio: Instant Artist            2011             0.1702          0.02
¡Shin Chan Flipa en colores!            2007             0.2800          0.14

[12130 rows x 2 columns]

### group the dataset by game name and platform, and then calculate the maximum, minimum, mean, and total North American sales for each combination?

In [210]:
group=df.groupby(['Game_Name','Platform'])['NA_Sales'].agg(['max','min','mean','sum'])
group.head()

                                                   max   min  mean   sum
Game_Name                               Platform
'98 Koshien                             PS        0.15  0.15  0.15  0.15
.hack//G.U. Vol.1//Rebirth              PS2       0.00  0.00  0.00  0.00
.hack//G.U. Vol.2//Reminisce            PS2       0.11  0.11  0.11  0.11
.hack//G.U. Vol.2//Reminisce (jp sales) PS2       0.00  0.00  0.00  0.00
.hack//G.U. Vol.3//Redemption           PS2       0.00  0.00  0.00  0.00

## idxmax()

In [219]:
df.loc[df['Global_Sales'].idxmin()]

Rank                      15983
Game_Name                 Turok
Platform                     PC
Year                       2008
Genre                    Action
Publisher            Touchstone
NA_Sales                    0.0
EU_Sales                   0.01
JP_Sales                    0.0
Other_Sales                 0.0
Global_Sales               0.01
Total_sales_ratio          0.01
Name: 15980, dtype: object

In [220]:
df.loc[df['Global_Sales'].idxmax()]

Rank                          1
Game_Name            Wii Sports
Platform                    Wii
Year                       2006
Genre                    Sports
Publisher              Nintendo
NA_Sales                  41.49
EU_Sales                  29.02
JP_Sales                   3.77
Other_Sales                8.46
Global_Sales              82.74
Total_sales_ratio       78.1346
Name: 0, dtype: object

### find the game with the highest maximum total sales ratio in the dataset?

In [221]:
df.groupby('Game_Name')['Total_sales_ratio'].max().idxmax()

'Wii Sports'

### find the game with the lowest minimum total sales ratio in the dataset?

In [222]:
df.groupby('Game_Name')['Total_sales_ratio'].min().idxmin()

'SCORE International Baja 1000: The Official Game'

## cut()
### categorize global sales into different ranks such as 'low', 'medium', 'high', and 'very high' based on specific sales ranges?

In [224]:
df['Global_Sales'].max()

82.74

In [225]:
df['Global_Sales'].min()

0.01

In [234]:
df['global_sales_rank']=pd.cut(df['Global_Sales'],bins=[0,25.00,50.00,75.00,df['Global_Sales'].max()],labels=['low','medium','high','veryhigh'])

In [233]:
df

,Rank,Game_Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_sales_ratio,global_sales,global_sales_rank
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,78.1346,veryhigh,veryhigh
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,46.2877,medium,medium
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,36.3431,medium,medium
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.3496,medium,medium
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,40.6100,medium,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.0100,NaN,low
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.0100,NaN,low
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0.0000,NaN,low
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.0100,NaN,low
16597,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.0100,NaN,low